-- ============================================================
-- Capsule - Local Knowledge OS
-- Migration: 001_schema_v1.sql
-- For: v1.0.0
-- Date: 2026-04-16
--
-- Purpose:
--   Fresh schema for v1.0.0. Locks the vector column to 768
--   dimensions (matching Ollama nomic-embed-text) and adds all
--   performance indexes needed for search to stay fast as data grows.
--
-- Safe to run on:
--   - A fresh install (nothing to drop, everything to create)
--   - A v1.0.0-pre install that was seeded before the bug was fixed
--     (wipes any existing embeddings - they'll be regenerated by the
--     repair script or on next save)
--
-- NOT safe to run on:
--   - A production install with embeddings you want to keep. But
--     there are none of those, because v1.0.0 is the first release.
--
-- Usage:
--   psql -d capsule -f migrations/001_schema_v1.sql
-- ============================================================

-- Make sure pgvector is loaded. Harmless if already installed.
CREATE EXTENSION IF NOT EXISTS vector;


-- ============================================================
-- Fix the vector column dimension.
--
-- Any v1.0.0-pre installation may have a 1536-dim vector column
-- left over from when the app defaulted to OpenAI embeddings.
-- Drop it and recreate at 768 for nomic-embed-text.
-- ============================================================

ALTER TABLE embeddings DROP COLUMN IF EXISTS vector;
ALTER TABLE embeddings ADD COLUMN vector vector(768);


-- ============================================================
-- Performance indexes.
--
-- Without these, every search does a sequential scan of every row
-- in embeddings. Fine at 7 rows, terrible at 50,000 chunks. At
-- Capsule's intended lifespan (years of personal conversations)
-- these aren't optional.
-- ============================================================

-- Speed up the entries <-> embeddings join. Used on every search,
-- every repair, every display-an-entry-with-its-chunks query.
CREATE INDEX IF NOT EXISTS idx_embeddings_entry_id
    ON embeddings (entry_id);

-- HNSW index on the vector column for fast similarity search.
-- Without this, ORDER BY vector <=> :query does a full table scan.
-- With this, search is O(log n) instead of O(n).
--
-- m=16, ef_construction=64 are pgvector defaults. Good balance
-- of build cost vs recall quality. At query time, hnsw.ef_search
-- can be raised (SET hnsw.ef_search = 100) for better recall if
-- the default isn't accurate enough.
--
-- vector_cosine_ops matches the <=> operator used in main.py's
-- search queries. Must match or the index won't be used.
CREATE INDEX IF NOT EXISTS idx_embeddings_vector_hnsw
    ON embeddings
    USING hnsw (vector vector_cosine_ops);

-- GIN index on tokenized entry content for fast full-text search.
-- Used by the text-search leg of hybrid search. Expression index
-- means we don't need a separate tsv column or a trigger to keep
-- it in sync.
CREATE INDEX IF NOT EXISTS idx_entries_raw_content_tsv
    ON entries
    USING GIN (to_tsvector('english', coalesce(raw_content, '')));

-- GIN index on entry titles. Short content but worth indexing —
-- title hits are often the most relevant results.
CREATE INDEX IF NOT EXISTS idx_entries_title_tsv
    ON entries
    USING GIN (to_tsvector('english', coalesce(title, '')));

-- Also index on chunk_text for text search at the chunk level,
-- once we start storing real chunk text (not just a truncation
-- of the whole entry).
CREATE INDEX IF NOT EXISTS idx_embeddings_chunk_text_tsv
    ON embeddings
    USING GIN (to_tsvector('english', coalesce(chunk_text, '')));


-- ============================================================
-- Verification: run these after the migration to confirm.
-- Lines are commented so the script runs cleanly; uncomment to use.
-- ============================================================

-- \d embeddings
-- \di idx_embeddings*
-- \di idx_entries*
